# Basic Colors
foreground              #{{ onSurface.hex }}
background              #{{ surface.hex }}
selection_foreground    #{{ surface.hex }}
selection_background    #{{ secondary.hex }}

# Cursor colors
cursor                  #{{ secondary.hex }}
cursor_text_color       #{{ surface.hex }}

# URL underline color
url_color               #{{ tertiary.hex }}

# Window border colors
active_border_color     #{{ primary.hex }}
inactive_border_color   #{{ surfaceVariant.hex }}
bell_border_color       #{{ error.hex }}

# Tab bar colors
active_tab_foreground   #{{ surface.hex }}
active_tab_background   #{{ primary.hex }}
inactive_tab_foreground #{{ onSurfaceVariant.hex }}
inactive_tab_background #{{ surfaceContainerLow.hex }}
tab_bar_background      #{{ surface.hex }}

# Terminal Colors
# black
color0 #{{ term0.hex }}
color8 #{{ term8.hex }}
# red
color1 #{{ term1.hex }}
color9 #{{ term9.hex }}
# green
color2 #{{ term2.hex }}
color10 #{{ term10.hex }}
# yellow
color3 #{{ term3.hex }}
color11 #{{ term11.hex }}
# blue
color4 #{{ term4.hex }}
color12 #{{ term12.hex }}
# magenta
color5 #{{ term5.hex }}
color13 #{{ term13.hex }}
# cyan
color6 #{{ term6.hex }}
color14 #{{ term14.hex }}
# white
color7 #{{ term7.hex }}
color15 #{{ term15.hex }}