$primary_paletteKeyColor = 7172ad
$secondary_paletteKeyColor = 76758b
$tertiary_paletteKeyColor = 946b82
$neutral_paletteKeyColor = 78767d
$neutral_variant_paletteKeyColor = 777680
$background = 040407
$onBackground = e4e1e9
$surface = 040407
$surfaceDim = 040407
$surfaceBright = 101012
$surfaceContainerLowest = 030305
$surfaceContainerLow = 07070b
$surfaceContainer = 08090c
$surfaceContainerHigh = 0c0c0f
$surfaceContainerHighest = 0f0f11
$onSurface = e4e1e9
$surfaceVariant = 131316
$onSurfaceVariant = c8c5d0
$inverseSurface = e4e1e9
$inverseOnSurface = 303036
$outline = 918f9a
$outlineVariant = 47464f
$shadow = 000000
$scrim = 000000
$surfaceTint = 252541
$primary = c1c1ff
$onPrimary = 2a2a60
$primaryContainer = 404178
$onPrimaryContainer = e1dfff
$inversePrimary = 585992
$secondary = c6c4dd
$onSecondary = 2f2f42
$secondaryContainer = 47475b
$onSecondaryContainer = e2e0f9
$tertiary = e9b9d3
$onTertiary = 46263a
$tertiaryContainer = b0849c
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = e1dfff
$primaryFixedDim = c1c1ff
$onPrimaryFixed = 14134a
$onPrimaryFixedVariant = 404178
$secondaryFixed = e2e0f9
$secondaryFixedDim = c6c4dd
$onSecondaryFixed = 1a1a2c
$onSecondaryFixedVariant = 454559
$tertiaryFixed = ffd8ec
$tertiaryFixedDim = e9b9d3
$onTertiaryFixed = 2f1124
$onTertiaryFixedVariant = 5f3c51
$term0 = 080808
$term1 = ab73ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 98aad8
$term5 = b39feb
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = bf94ff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b5c1dd
$term13 = c9b5f5
$term14 = bae0ff
$term15 = ffffff
$rosewater = f7eff9
$flamingo = e8def3
$pink = e1d8ff
$mauve = beb8ff
$red = c0a5fe
$maroon = c9b5ed
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = d3dfff
$sky = cfdaff
$sapphire = b7c5ff
$blue = b0b8ff
$lavender = c7c8ff
$klink = 7282d2
$klinkSelection = 7282d2
$kvisited = 8072da
$kvisitedSelection = 8072da
$knegative = a068ff
$knegativeSelection = a068ff
$kneutral = c893ff
$kneutralSelection = c893ff
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e4e1e9
$subtext1 = c8c5d0
$subtext0 = 918f9a
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161516
$surface2 = 121213
$surface1 = 0d0d10
$surface0 = 060609
$base = 000001
$mantle = 000001
$crust = 000001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
