$primary_paletteKeyColor = 2b8292
$secondary_paletteKeyColor = 637b81
$tertiary_paletteKeyColor = 6d7698
$neutral_paletteKeyColor = 72787a
$neutral_variant_paletteKeyColor = 70797b
$background = 020506
$onBackground = dee3e5
$surface = 020506
$surfaceDim = 020506
$surfaceBright = 0f1111
$surfaceContainerLowest = 010304
$surfaceContainerLow = 050809
$surfaceContainer = 060a0a
$surfaceContainerHigh = 0a0d0d
$surfaceContainerHighest = 0e1010
$onSurface = dee3e5
$surfaceVariant = 111415
$onSurfaceVariant = bfc8cb
$inverseSurface = dee3e5
$inverseOnSurface = 2b3133
$outline = 899295
$outlineVariant = 3f484b
$shadow = 000000
$scrim = 000000
$surfaceTint = 002d34
$primary = 83d2e4
$onPrimary = 00363f
$primaryContainer = 004e5a
$onPrimaryContainer = a4eeff
$inversePrimary = 006877
$secondary = b2cbd1
$onSecondary = 1c3439
$secondaryContainer = 354d52
$onSecondaryContainer = cde7ee
$tertiary = bdc5eb
$onTertiary = 262f4d
$tertiaryContainer = 878fb3
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = a4eeff
$primaryFixedDim = 83d2e4
$onPrimaryFixed = 001f25
$onPrimaryFixedVariant = 004e5a
$secondaryFixed = cde7ee
$secondaryFixedDim = b2cbd1
$onSecondaryFixed = 051f24
$onSecondaryFixedVariant = 334a50
$tertiaryFixed = dce1ff
$tertiaryFixedDim = bdc5eb
$onTertiaryFixed = 111a37
$onTertiaryFixedVariant = 3d4565
$term0 = 080808
$term1 = 8383ff
$term2 = 41e1db
$term3 = 75fcdd
$term4 = 77b4bf
$term5 = 7aaee9
$term6 = 80d7db
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 00f6f0
$term11 = c9fff3
$term12 = a4c7cb
$term13 = a2c0f7
$term14 = 87ebee
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = bbe2ff
$mauve = 70cbf7
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d0f9f3
$green = 8af0f4
$teal = 9fecf7
$sky = 96e7f9
$sapphire = 76d4ec
$blue = 62c9eb
$lavender = 8ed6f5
$klink = 0093b1
$klinkSelection = 0094b1
$kvisited = 008abb
$kvisitedSelection = 008abb
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bbc4
$kpositiveSelection = 00bbc4
$text = dee3e5
$subtext1 = bfc8cb
$subtext0 = 899295
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 151616
$surface2 = 111213
$surface1 = 0b0e0f
$surface0 = 040708
$base = 000101
$mantle = 000101
$crust = 000101
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
